### ISSUE TITLE
showBarModalBottomSheet - backgroundColor does not seem to be used anywhere and does not change the background color

### ISSUE THREAD

**Issue by vasilich6107** [jamesblasco/modal_bottom_sheet#237]
Hi @jamesblasco 
Thanks for your work.

Recently I tried to use `backgroundColor` without success.
The prop does not seem to be passed anywhere(besides initial function) so it is no surprise that is does not work as expected
<img width="477" alt="image" src="https://user-images.githubusercontent.com/6721286/163572667-ffb8d55a-d664-4fd6-909c-91fba4f6ec7c.png">

**Comment by Zechst** [comment]
Hey, same here with this issue. The modal color doesn't seem to change

**Comment by seljmov** [comment]
Hi, @jamesblasco! You can use my repository until my update is accepted.

```
modal_bottom_sheet:
  git:
    url: https://github.com/seljmov/modal_bottom_sheet.git
    ref: fix_bar_color
```
