### ISSUE TITLE
"maintainState => false" in ModalBottomSheetRoute Causes Modal State to get Discarded

### ISSUE THREAD

**Issue by hsynaksu** [jamesblasco/modal_bottom_sheet#255]
``Hello!
In this [commit](https://github.com/jamesblasco/modal_bottom_sheet/commit/6ed1b1dea9c367286fc68701f6dbec277b30f97f) it seems bool get maintainState => false; was added. This causes modal content to get discarded when a new route is pushed and popped. Normally state is maintained during navigation so this feels like a mistake to me and causes some problems in our project. I was wondering the reason behind this and if we can change this to true? 

Edit:
For anyone having this issue, you can use my fork, I only changed that line to true:
```yaml
  modal_bottom_sheet:
    git:
      url: https://github.com/hsynaksu/modal_bottom_sheet
```
