### ISSUE TITLE
Not compatible with flutter 3.13.0

### ISSUE THREAD

**Issue by river2202** [jamesblasco/modal_bottom_sheet#366]
Got following error
```
../../../../../.pub-cache/hosted/pub.dev/sheet-1.0.0-pre/lib/src/scrollable.dart:313:7: Error: The non-abstract class 'SheetState' is missing implementations for these members:
 - ScrollContext.devicePixelRatio
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class SheetState extends State<SheetScrollable>
```

**Comment by maRci002** [comment]
PR #365 should resolve this problem. The current workaround for using the PR commit in `pubspec.yaml` is: (_if you are using the `sheet` package directly, then override it in `dependencies`. If you are using the `modal_bottom_sheet` package, then override it in `dependency_overrides`_)

```yaml
dependency_overrides:
  sheet:
    git:
      url: https://github.com/jamesblasco/modal_bottom_sheet.git
      ref: 471c15c92b1410a710020de01569b74535456ddd
      path: sheet
```
